#!/bin/sh
# Redeploy a pycsw stack generated by configurator/collection_mapping.py.
#
#   sh update_service.sh <service>            full teardown + redeploy
#   sh update_service.sh <service> --restart  restart the running container only
#   sh update_service.sh --all                redeploy every generated service
#
# <service> is the `name` of an entry in configurator/csw_endpoints.yml; its
# files are read from artifacts/deploy/<service>/ (override with DEPLOY_DIR).
#
# Secrets are never written to the generated files: they are loaded here from
# .env (override with ENV_FILE) and forwarded to the container by the stack
# file. --restart keeps the deployed spec, so it picks up edited plugin sources
# and pycsw.yml but NOT a changed .env or stack.yml — redeploy for those.
set -eu

usage() {
    sed -n '2,7p' "$0" | cut -c3-
    exit 1
}

[ $# -ge 1 ] || usage
STACK=$1
MODE=${2:-}

REPO_DIR=$(cd "$(dirname "$0")" && pwd)
DEPLOY_DIR=${DEPLOY_DIR:-$REPO_DIR/artifacts/deploy}
ENV_FILE=${ENV_FILE:-$REPO_DIR/.env}
STACK_FILE=$DEPLOY_DIR/$STACK/stack.yml

if [ "$STACK" = "--all" ]; then
    found=0
    for stack_file in "$DEPLOY_DIR"/*/stack.yml; do
        [ -f "$stack_file" ] || continue
        found=1
        sh "$0" "$(basename "$(dirname "$stack_file")")"
    done
    if [ "$found" = 0 ]; then
        echo "ERROR: nothing generated under $DEPLOY_DIR (run configurator/collection_mapping.py)" >&2
        exit 1
    fi
    exit 0
fi

case "$MODE" in
    --restart)
        docker service update --force "${STACK}_pycsw"
        exit 0
        ;;
    "") ;;
    *) usage ;;
esac

if [ ! -f "$STACK_FILE" ]; then
    echo "ERROR: $STACK_FILE not found." >&2
    echo "Generate it with: python configurator/collection_mapping.py $STACK" >&2
    exit 1
fi

if [ -f "$ENV_FILE" ]; then
    set -a
    . "$ENV_FILE"
    set +a
else
    echo "WARNING: $ENV_FILE not found (copy .env.example); relying on the current environment." >&2
fi
export REPO_DIR

# Fail on unset variables before tearing the running stack down.
docker stack config -c "$STACK_FILE" > /dev/null

docker stack rm "$STACK"
# The stack's overlay network is removed asynchronously; deploying before it
# is gone fails, so wait for it instead of sleeping a fixed time.
tries=0
while [ -n "$(docker network ls -q --filter "label=com.docker.stack.namespace=$STACK")" ] \
   || [ -n "$(docker ps -q --filter "label=com.docker.stack.namespace=$STACK")" ]; do
    tries=$((tries + 1))
    if [ "$tries" -gt 60 ]; then
        echo "ERROR: stack $STACK was not fully removed after 60s" >&2
        exit 1
    fi
    sleep 1
done

docker stack deploy -c "$STACK_FILE" "$STACK"
